### ISSUE TITLE
Not news?

### ISSUE THREAD

**Issue by dpunx** [sakoula/XiaoMi-Air-6200U#2]
Hi!

For me this is the best source for this notebook but I see that not work with the last hack.

I've updated all kext and clover, update the osx and when log in... Black screen with mouse. And nothing more.

Somebody can help? Other githubs sources not work

Thanks

**Comment by asnfohsdgfbkxcv** [comment]
maye this will be working. https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen

**Comment by sakoula** [comment]
hi I have updated the guide recently and it works for 10.14.5 and 10.14.6. 

sure you can try the johnnync13 

on my guide I try to keep only the absolutely minimum configuration and reason every choice of configuration I make
