### ISSUE TITLE
Instructions not working

### ISSUE THREAD

**Issue by DiegoBM** [sakoula/XiaoMi-Air-6200U#4]
Hi

I'm trying to follow your steps as exact as possible but the installation won't work.

If I do it exactly as you mention with the same version of clover that you recommend to use, my xiaomi (is the same one you indicate with bios a06), won't find the usb.
I've also tried using the latest uefi version of clover but if I copy the files you mention, the installer will halt and reboot because of a panic error slightly after I can see the apple logo.

Maybe there is something I'm doing wrong since a couple of steps are not clear (for how far I could reach):
In step 3.5 you mention:

Clover for UEFI booting only, Install Clover in the ESP

which I'm not sure what you mean. On the clover installer I chose the "Install macOS Mojave" as destination, and I presume that is all because is the only thing I can do. Right after that you show two list of drivers UEFI and FIREVAULT but you don't indicate what do we need to do regarding that.

After that, on step 3.6 you instruct to "Mount the USB Flash Drive's EFI partition on /Volumes/EFI" but after using the version of clover that you mention, I cannot see any UEFI partition. The EFI folder is copied into the"Install macOS mojave" partition, so I copy the files you recommend there.

Hope you can help.

**Comment by DiegoBM** [comment]
Apologies, I was using an old post version from tonymacx86 (https://www.tonymacx86.com/threads/guide-xiaomi-mi-air-13-3-skylake-u-2016-1rst-gen.268979/). Folowing the github version seems to work well up to the installation point. If I find any issues while using the github version, I'll report it here

**Comment by sakoula** [comment]
yes I really need to update my tonymac post :)
