### ISSUE TITLE
Touchpad is acting up

### ISSUE THREAD

**Issue by DiegoBM** [sakoula/XiaoMi-Air-6200U#5]
Hi all,

I have completed the installation of Mojave 10.14.6 and everything seems to be more or less ok besides the touchpad which doesn't seem to either support regular left or right clicks. This is noticeable the minute that macOS loads, when I try to open finder from the dock, it will complaint with a message reading "No Available Windows". Likewise I'm not capable of opening desktop folders. It's as if it were clicking hundreds of times with one single touch. Hope you guys can help me to get it working properly. Thank you in advance.

Update: from my research so far, I'd say that it's due to force touch. I have tried changing the kext in /Library/Extensions with the latest version of acidanthera's VoodooPS2Controller (2.03), and recompiling the kernel cache (with  sudo kextcache -i /) after changin owner and mode, but that doesn't seem to solve the issue. Is there any way that it could be disabled forceTouch without compiling? I have no experience compiling macOS projects. There is supposed to be a trackpad panel on macos system properties where you should be able to disable that, but in my installation it says it couldn't find any trackpads

**Comment by DiegoBM** [comment]
I managed to compile a voodoops2controller version with force touch disabled and now everything works beatufully touchwise. The trackpad is still not recognised on the system settings panel, but I guess that's a separate issue. Closing.

**Comment by sakoula** [comment]
Hello,
Well I used to use RehabMan's [OS-X-Voodoo-PS2-Controller](https://bitbucket.org/RehabMan/os-x-voodoo-ps2-controller/downloads/) which did not support multitouch gestures and I switched recently to acidanthera's [acidanthera/VoodooPS2 (2.0.1.1)](https://github.com/acidanthera/VoodooPS2) which works for me and this is the one I include in the repository. 

Which one was not working for you?  Was the one from the repository? Try installing the latest one [2.0.3](https://github.com/acidanthera/VoodooPS2/releases) . Be careful where to install it and update the kernel caches. 

Let me know if it works.

BTW which BIOS version do you have?

Also check [documentation](https://github.com/acidanthera/VoodooPS2) to use the trackpad in another mode to fix your problems.

**Comment by DiegoBM** [comment]
Hi @sakoula , I tried both, the repository one and version 2.0.3 from acidanthera's repo but none of them worked. I finally built it myself from the master version in acidanthera's repo disabling, force touch from info.plist, this one worked for me. Maybe I have a different trackpad version but I reckon that xiaomi didn't build variations of the gefore 940mx version of the laptop.

**Comment by sakoula** [comment]
Try also the RehabMan's one. I do not have the laptop with me. I will check whether I did something else that I have not documented. I upgraded from 10.14.5 to 10.14.6 . 

During the installation did you have problems with clicking?

**Comment by DiegoBM** [comment]
Not that I can remember no, it went smoothly, but they might not be processing force input during the installer. If you could check when you have your laptop if your system settings can recognise the trackpad it would be good to know.

Udate: After installing a battery in the laptop (I was running it directly plugged to the AC without battery since I was waiting for a new one to arrive), it can also recognise my trackpad. I'm wondering if it might be the reason why I was having issues?

**Comment by sakoula** [comment]
hey @DiegoBM this may be the problem? Anyway mine is working both softclick (tapping) and hardclick. And I have exactly the same config as in the repository in Github.

And my trackpad appears in the preferences.

Are you still having problems?

**Comment by DiegoBM** [comment]
Thank you for asking @sakoula. At the moment everything seems to be working fine and smooth, even more than what I originally expected (missing the GPU acceleration but I guess that it can't be helped). I kept my own built  voodoo kext with force touch disabled since it was working just fine, so I don't know yet if it was the lack of battery the culprit... If I need to go through the installation again (presumably when I try to upgrade to Catalina, since it's my first time upgrading a hackintosh, I guess that everything will go wrong), then I'll use the voodoo kext in the repository and I will confirm. In the meantime I guess that we can close this issue.

**Comment by sakoula** [comment]
I will also upgrade to catalina but I guess I will wait for a month until all the modules/clover/kexts will get into a 'steady state'. Also I am always consulting the excellent https://github.com/daliansky/XiaoMi-Pro-Hackintosh guide before going into any major changes. The hardware is not the same but there are enough similarities

**Comment by SKYCrap** [comment]
Could you please provide this version with forcetouch disabled?
