### ISSUE TITLE
Attempting system restart

### ISSUE THREAD

**Issue by miguelssimao** [sakoula/XiaoMi-Air-6200U#6]
Hello,
I've followed this guide using the specified clover version and Mojave.
I already tried the installation guide two times, but I everytime I try to boot from the USB to install macOS, it gives me an "Attempting system restart" error. It happens very quickly as it immediately restarts so I'm not sure in what line it happens, but it doesn't even land on the Installation window.

What could it be?

**Comment by sakoula** [comment]
which bios do you have on your laptop? do you get to the clover screen? did you make all the bios settings required? attach your efi partition of the usb stick to check it out. have you tried with a different usb stick? also how did you make the usb stick? did you download mojave from the apple store and on the same computer you created the usb stick?

**Comment by miguelssimao** [comment]
BIOS Version is XMAKB3M0P0705. Is it outdated? I did make all the bios settings required.
I did get to the clover screen, indeed. And yes, the whole process of Mojave and the USB was done on a Mac OS X VM.

**Comment by miguelssimao** [comment]
Sorry, just realized the guide is for the 2016 version, and I have the 2017.
