### ISSUE TITLE
do you plan to update, so we can update Catalina?

### ISSUE THREAD

**Issue by victorsnk** [sakoula/XiaoMi-Air-6200U#7]
Hi! How are yo? By any chance do you plan to update, so we can update Catalina? Thank you very much. My laptop spec.: [Xiaomi Mi Air 13.3 Skylake-U 2016](https://victoraf.gitlab.io/posts/2019/12/mi-hardware-2019/) - Laptop - 

Thanks for your great work!

**Comment by johnnynunez** [comment]
@victorsnk https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen

**Comment by sakoula** [comment]
Hi, I am planning to upgrade within February and update my guide. 

I have not tried @johnnync13  's EFI folder.

**Comment by UnknownH** [comment]
Is this guide still valid for 10.15.6 or .7? I reckon that clover 5099 won't work for those versions. Or can we use the clover customizations that you can see in the guide with the latest versions of clover?

**Comment by sakoula** [comment]
Hi everyone, I updated the guide to be able to support 10.15.3 up to 10.15.7 and the upcoming BigSur release. I have migrated to OpenCore and it is working great! I have tested my machine quite extensively with this setup.

I will also update the guide within a couple of weeks of the BigSur release.

@johnnync13 I think the repository you are pointing to is quite bloated with all shorts of older patches which some of them are old and some of them should not be used at all. Also the latest release that you have on the repository does not even boot to the opencore menu.

Let me know if you have any issue.

**Comment by simowce** [comment]
> Hi everyone, I updated the guide to be able to support 10.15.3 up to 10.15.7 and the upcoming BigSur release. I have migrated to OpenCore and it is working great! I have tested my machine quite extensively with this setup.
> 
> I will also update the guide within a couple of weeks of the BigSur release.
> 
> @johnnync13 I think the repository you are pointing to is quite bloated with all shorts of older patches which some of them are old and some of them should not be used at all. Also the latest release that you have on the repository does not even boot to the opencore menu.
> 
> Let me know if you have any issue.

Hi, does shutdown work as expected on 10.15.7?

**Comment by sakoula** [comment]
no shutdown is not working as expected in 10.15.7, 11.0.1 . It is not clear to me why this is happening and most likely it requires some time of ACPI patching.
