### ISSUE TITLE
Boot loop - When Updating to Big Sur

### ISSUE THREAD

**Issue by dberrocal-git** [sakoula/XiaoMi-Air-6200U#8]
I updated my Efi partition with you v8.0 edited my SMBIOS, restarted and everything was working well, even the intel Wifi.

I updated to Big Sur from System Preferences, and after the update, the system boot loops in the Appel logo and restarts.  Cant 
put it to verbose cmd - v not working, any ideas to recover the system witout reinstalling all? 

**Solution:**
 - Enter in recovery and mout your EFI partition, edit config.plist with vim and enable verbose in boot-arg ( -v )

If the system says: "Rooting from the live fs of a sealed volume is not allowed on RELEASE.."

 - Disable Apple secure boot in config.plist (SecureBootModel=Disabled, not Default) (Open core 6.2 bug)

Some Extra Notes: 

- The: "AIR_EFI to /Volumes/EFI and rename it to EFI. It will look like /Volumes/EFI/EFI"  may be wrong for windows users:
    * Final Folder (DRIVE LETER):/EFI
                                               -/BOOT
                                               -/OC

**Comment by sakoula** [comment]
hi there,

sorry for this. I have reuploaded v8.0. the one now is having the missing BOOT directory plus a couple of optional opencore tools. Let me know if that foxed your problem.
