### ISSUE TITLE
when could we have next update?

### ISSUE THREAD

**Issue by cuinchy3** [sakoula/XiaoMi-Air-6200U#9]
So far,I find some problems that influence my use:
 
1.Intel WiFi can't drive,I still use itlwm(Heliport).

2.shutdown is not work，the keyboard light is always on.

3.Bluetooth can't attach my device.

**Comment by sakoula** [comment]
hi @cuinchy3  and happy new year. I just found this issue opened. I have made a couple of releases. I hope you found them useful.

Best regards,
sakoula
